# tickers.py — Static ticker lists for NSE Nifty 500 and NYSE large-caps

NIFTY500_TICKERS = [
    # Nifty 500 constituents with .NS suffix for yfinance
    "RELIANCE.NS", "TCS.NS", "HDFCBANK.NS", "BHARTIARTL.NS", "ICICIBANK.NS",
    "INFOSYS.NS", "SBIN.NS", "HINDUNILVR.NS", "ITC.NS", "LT.NS",
    "KOTAKBANK.NS", "HCLTECH.NS", "AXISBANK.NS", "BAJFINANCE.NS", "WIPRO.NS",
    "MARUTI.NS", "SUNPHARMA.NS", "ULTRACEMCO.NS", "TITAN.NS", "ONGC.NS",
    "NTPC.NS", "POWERGRID.NS", "TATAMOTORS.NS", "ADANIENT.NS", "M&M.NS",
    "NESTLEIND.NS", "JSWSTEEL.NS", "TATASTEEL.NS", "BAJAJFINSV.NS", "DRREDDY.NS",
    "CIPLA.NS", "DIVISLAB.NS", "TECHM.NS", "HINDALCO.NS", "COALINDIA.NS",
    "GRASIM.NS", "BPCL.NS", "INDUSINDBK.NS", "EICHERMOT.NS", "BRITANNIA.NS",
    "APOLLOHOSP.NS", "HEROMOTOCO.NS", "SBILIFE.NS", "HDFCLIFE.NS", "ADANIPORTS.NS",
    "TATACONSUM.NS", "BAJAJ-AUTO.NS", "UPL.NS", "VEDL.NS", "SHREECEM.NS",
    "PIDILITIND.NS", "GODREJCP.NS", "TORNTPHARM.NS", "BIOCON.NS", "DABUR.NS",
    "BERGEPAINT.NS", "MARICO.NS", "COLPAL.NS", "HAVELLS.NS", "LUPIN.NS",
    "MCDOWELL-N.NS", "SIEMENS.NS", "ABB.NS", "BOSCHLTD.NS", "MOTHERSON.NS",
    "BALKRISIND.NS", "MUTHOOTFIN.NS", "CHOLAFIN.NS", "AUBANK.NS", "FEDERALBNK.NS",
    "IDFCFIRSTB.NS", "BANDHANBNK.NS", "PNB.NS", "BANKBARODA.NS", "CANBK.NS",
    "UNIONBANK.NS", "INDIANB.NS", "IOB.NS", "CENTRALBK.NS", "UCOBANK.NS",
    "MAHABANK.NS", "LICHSGFIN.NS", "PIRAMALENT.NS", "MANAPPURAM.NS", "RBLBANK.NS",
    "KARURVYSYA.NS", "DCBBANK.NS", "SOUTHBANK.NS", "UJJIVANSFB.NS", "EQUITASBNK.NS",
    "NAUKRI.NS", "ZOMATO.NS", "PAYTM.NS", "POLICYBZR.NS", "DELHIVERY.NS",
    "IRCTC.NS", "RAILVIKAS.NS", "RVNL.NS", "IRFC.NS", "RECLTD.NS",
    "PFC.NS", "HUDCO.NS", "NBCC.NS", "NLC.NS", "SJVN.NS",
    "NHPC.NS", "TORNTPOWER.NS", "CESC.NS", "TATAPOWER.NS", "ADANIGREEN.NS",
    "ADANITRANS.NS", "ADANIPOWER.NS", "JSW Energy.NS", "RPOWER.NS", "INOXWIND.NS",
    "SUZLON.NS", "GREENKO.NS", "RENEW.NS", "WAAREEENER.NS", "PREMIER.NS",
    "DLF.NS", "GODREJPROP.NS", "OBEROIRLTY.NS", "PRESTIGE.NS", "PHOENIXLTD.NS",
    "MAHINDCIE.NS", "BRIGADE.NS", "SOBHA.NS", "PURVA.NS", "KOLTEPATIL.NS",
    "ASIANPAINT.NS", "KANSAINER.NS", "AKZOINDIA.NS", "INDIGO.NS", "SPICEJET.NS",
    "INTERGLOBE.NS", "BLUEDART.NS", "GATI.NS", "MAHLOG.NS", "VRL.NS",
    "ZYDUSLIFE.NS", "ALKEM.NS", "IPCALAB.NS", "AUROPHARMA.NS", "NATCOPHARM.NS",
    "GRANULES.NS", "LAURUSLABS.NS", "GLENMARK.NS", "PFIZER.NS", "GLAXO.NS",
    "ABBOTINDIA.NS", "SANOFI.NS", "NOVARTIS.NS", "WOCKPHARMA.NS", "AJANTPHARM.NS",
    "JBCHEPHARM.NS", "ERIS.NS", "CAPLIPOINT.NS", "SOLARA.NS", "SEQUENT.NS",
    "TATAELXSI.NS", "LTTS.NS", "MPHASIS.NS", "PERSISTENT.NS", "COFORGE.NS",
    "HEXAWARE.NS", "NIITLTD.NS", "KPITTECH.NS", "TANLA.NS", "ROUTE.NS",
    "MASTEK.NS", "ZENSAR.NS", "MINDTREE.NS", "RAMSARUP.NS", "ECLERX.NS",
    "INFOEDGE.NS", "JUSTDIAL.NS", "INDIAMART.NS", "CARTRADE.NS", "EASEMYTRIP.NS",
    "HAPPSTMNDS.NS", "BIRLASOFT.NS", "CYIENT.NS", "SONATSOFTW.NS", "INTELLECT.NS",
    "RAILTEL.NS", "TATACOMM.NS", "STLTECH.NS", "GTLINFRA.NS", "TEJASNET.NS",
    "DIXON.NS", "AMBER.NS", "PG.NS", "VOLTAS.NS", "BLUESTAR.NS",
    "LLOYDSENGG.NS", "VGUARD.NS", "SYMPHONY.NS", "WHIRLPOOL.NS", "BAJAJCON.NS",
    "CROMPTON.NS", "ORIENTELEC.NS", "RAJESHEXPO.NS", "TITAN.NS", "KALYAN.NS",
    "PCJEWELLER.NS", "SENCO.NS", "THANGAMAYL.NS", "TRIBHOVAND.NS", "IIFL.NS",
    "MOFSL.NS", "ANGELONE.NS", "5PAISA.NS", "ICICIGI.NS", "ICICIPRULI.NS",
    "HDFCAMC.NS", "NIPPONSLIFE.NS", "ABSLAMC.NS", "UTIAMC.NS", "BFUTL.NS",
    "SHRIRAMPPS.NS", "BAJAJHLDNG.NS", "MAHINDRA.NS", "TATAHOLDING.NS", "MUTHOOTCAP.NS",
    "SUNDARMFIN.NS", "LTFH.NS", "IBULHSGFIN.NS", "CANFINHOME.NS", "AAVAS.NS",
    "HOMEFIRST.NS", "REPCO.NS", "APTUS.NS", "PNBHOUSING.NS", "GRUH.NS",
    "MMTC.NS", "MSTCLTD.NS", "IRCON.NS", "BEML.NS", "BEL.NS",
    "HAL.NS", "MIDHANI.NS", "MAZAGON.NS", "COCHINSHIP.NS", "GARDENRCH.NS",
    "GRINDWELL.NS", "CARBORUNIV.NS", "CUMI.NS", "GREAVESCOT.NS", "ESCORTS.NS",
    "ATUL.NS", "SRF.NS", "PIIND.NS", "RALLIS.NS", "DHANUKA.NS",
    "BAYER.NS", "SUMICHEM.NS", "NAVIN.NS", "CLEAN.NS", "AARTI.NS",
    "VINATIORGA.NS", "GALAXY.NS", "FINEORG.NS", "PCBL.NS", "PHILIPCARB.NS",
    "MANALI.NS", "NOCIL.NS", "BASF.NS", "DEEPAKNTR.NS", "TATACHEM.NS",
    "GNFC.NS", "GSFC.NS", "CHAMBLFERT.NS", "COROMANDEL.NS", "KSCL.NS",
    "ASTRAL.NS", "SUPREMEIND.NS", "NILKAMAL.NS", "VINYLINDIA.NS", "EPL.NS",
    "UFLEX.NS", "HUHTAMAKI.NS", "MOLD-TEK.NS", "JYOTHYLAB.NS", "TTKPRESTIG.NS",
    "HAWKINCOOK.NS", "VSTIND.NS", "GODFRYPHLP.NS", "RADICO.NS", "TILAKNAGAR.NS",
    "UNITDSPR.NS", "GLOBUSSPR.NS", "JUBLFOOD.NS", "WESTLIFE.NS", "DEVYANI.NS",
    "SAPPHIRE.NS", "BARBEQUE.NS", "SPECIALITY.NS", "MAHINDLIFE.NS", "CEATLTD.NS",
    "APOLLOTYRE.NS", "MRF.NS", "JKTYRE.NS", "GOODYEAR.NS", "BALKRISIND.NS",
    "EXIDEIND.NS", "AMARAJABAT.NS", "HBLPOWER.NS", "LUMINOUS.NS", "SOLARIND.NS",
    "SUNFLAG.NS", "RATNAMANI.NS", "WELSPUNIND.NS", "VARDHACRLC.NS", "TRIDENT.NS",
    "GRASIM.NS", "CENTURY.NS", "JSWHL.NS", "SINTERCAST.NS", "TINPLATE.NS",
    "WELCORP.NS", "MANALIPETC.NS", "STERLINWIL.NS", "KIRI.NS", "SUDARSCHEM.NS",
]

# Remove duplicates while preserving order
_seen = set()
NIFTY500_TICKERS_CLEAN = []
for t in NIFTY500_TICKERS:
    if t not in _seen:
        _seen.add(t)
        NIFTY500_TICKERS_CLEAN.append(t)
NIFTY500_TICKERS = NIFTY500_TICKERS_CLEAN


NYSE_TICKERS = [
    # Large-cap NYSE stocks (S&P 500 / Dow components)
    "JPM", "BAC", "WFC", "C", "GS", "MS", "AXP", "BLK", "SCHW", "USB",
    "PNC", "TFC", "COF", "MTB", "RF", "KEY", "CFG", "HBAN", "FITB", "ZION",
    "XOM", "CVX", "COP", "SLB", "EOG", "MPC", "PSX", "VLO", "OXY", "HES",
    "PFE", "JNJ", "ABT", "MRK", "BMY", "LLY", "UNH", "CVS", "CI", "HUM",
    "WMT", "TGT", "KR", "COST", "DG", "DLTR", "SYY", "KHC", "GIS", "CAG",
    "K", "CPB", "HSY", "MKC", "SJM", "HRL", "TSN", "TAP", "STZ", "BF.B",
    "PG", "CL", "KMB", "CHD", "EL", "REV", "SPB", "NWL", "HPC", "UN",
    "KO", "PEP", "MNST", "KDP", "WK", "COKE", "FIZZ", "CELH", "REED", "NRDS",
    "MCD", "YUM", "QSR", "DPZ", "DENN", "CAKE", "DRI", "BLMN", "EAT", "TXRH",
    "DIS", "PARA", "FOX", "FOXA", "WBD", "NYT", "NWS", "OMC", "IPG", "WPP",
    "BA", "LMT", "RTX", "NOC", "GD", "L3H", "HII", "TDG", "SPR", "HEICO",
    "CAT", "DE", "EMR", "ETN", "PH", "ITW", "DOV", "FTV", "AME", "ROP",
    "GE", "HON", "MMM", "IR", "XYL", "FLOW", "GTLS", "ENPRO", "GNRC", "REXNORD",
    "UPS", "FDX", "JBHT", "ODFL", "XPO", "CHRW", "R", "EXPD", "MATX", "SAIA",
    "T", "VZ", "LUMN", "CTL", "FYBR", "ATUS", "CABO", "CNSL", "TDS", "USM",
    "NEM", "FCX", "AA", "X", "CLF", "NUE", "STLD", "RS", "CMC", "SCHN",
    "DD", "DOW", "LYB", "EMN", "IFF", "ALB", "CE", "HUN", "OLN", "TROX",
    "NEE", "DUK", "SO", "D", "AEP", "EXC", "SRE", "PEG", "ED", "EIX",
    "AMT", "CCI", "SPG", "PSA", "EQR", "AVB", "DRE", "VTR", "WELL", "HCP",
    "CVS", "MCK", "ABC", "CAH", "PDCO", "OMI", "PSA", "WAT", "TMO", "PKI",
    "BDX", "BSX", "EW", "STE", "HOLX", "BAX", "ZBH", "VAR", "ALGN", "DXCM",
    "MMC", "AON", "MKL", "TRV", "ALL", "PRU", "MET", "AFL", "GL", "LNC",
    "IBM", "HPE", "HPQ", "NCR", "DXC", "CSRA", "LDOS", "BAH", "CACI", "SAIC",
    "F", "GM", "STLA", "TM", "HMC", "RACE", "PAG", "AN", "KMX", "LAD",
    "HD", "LOW", "WSM", "RH", "BBBY", "PIR", "FND", "LL", "WHR", "ETH",
    "LEN", "DHI", "PHM", "TOL", "MDC", "MTH", "MHO", "LGIH", "BZH", "HOV",
    "SHW", "PPG", "RPM", "FUL", "AXTA", "HXL", "TRS", "ARES", "CW", "CRS",
    "IP", "PKG", "SEE", "SON", "GEF", "CLW", "KS", "ATR", "BERY", "SLGN",
    "CB", "HIG", "WRB", "MKL", "CINF", "HMN", "UNM", "GEV", "VST", "PCG",
    "BX", "KKR", "APO", "CG", "ARES", "OWL", "GAIN", "MAIN", "CEG", "ETR",
    "FE", "AES", "NRG", "URI", "RSG", "WM",
]

# Remove duplicates
_seen2 = set()
NYSE_TICKERS_CLEAN = []
for t in NYSE_TICKERS:
    if t not in _seen2:
        _seen2.add(t)
        NYSE_TICKERS_CLEAN.append(t)
NYSE_TICKERS = NYSE_TICKERS_CLEAN


def get_tickers(market: str):
    """Return ticker list for a given market ('NSE' or 'NYSE')."""
    if market.upper() == "NSE":
        return NIFTY500_TICKERS
    elif market.upper() == "NYSE":
        return NYSE_TICKERS
    else:
        raise ValueError(f"Unknown market: {market}. Use 'NSE' or 'NYSE'.")
